apiVersion: apps/v1
kind: Deployment
metadata:
  name: test4
  namespace: openfaas-fn
spec:
  selector:
    matchLabels:
      run: test4
  replicas: 1
  template:
    metadata:
      labels:
        run: test4
    spec:
      containers:
       - name: test4
         image: stevef1uk/test4-arm
         env:
         - name: PORT
           value: "5000"
         - name: HOST
           value: "0.0.0.0"
         - name: CASSANDRA_SERVICE_HOST
           value: "cassandra.cassandra.svc.cluster.local"
